# Atoms and Molecular Geometry

## Geometry and Coordinates in 3D Space

We can use the `numpy` library to create double-precision 3-vectors to use for coordinates:

In [15]:
import numpy as np
def coord(x,y,z): return np.array([x,y,z],np.double)

Double precision variables, 64-bit precision floating-point numbers, are the standard datatype for most scientific programming applications, and will be used throughout the rest of the course.

`numpy` makes it easy to compute distances:

In [40]:
def distance(pt1,pt2): return np.linalg.norm(pt1-pt2)

Here we use the `norm` method of numpy arrays to compute the *2-norm* of the difference between the two vectors, corresponding to the normal distance computed via the Pythagorean theorem
$$ r_{12} = \sqrt{(x_1-x_2)^2 + (y_1-y_2)^2 + (z_1-z_2)^2}.$$

We have not specified units for the distance function. If the xyz-coordinates correspond to meters, `distance` will return meters; if they correspond to Angstroms ($=10^{-10} m$), `distance` will return Angstroms. This ambiguity is a both a convenient polymorphism, in that we don't have to define different functions for different units, and a future source of errors if we try to compute distances between one point that has meter units and another that uses Angstroms.

A rigorous *type system* can substantially reduce the ambiguity, often without reducing the polymorphism, but is beyond the scope of the current work.

## Computing neighbor lists

Many of the forces encountered in computational chemistry are *pairwise*, and computing distances to other atoms is a common operation.

In [10]:
def distances(pt,others):
    ds = []
    for other in others:
        ds.append(distance(pt,other))
    return ds

We can make this syntax somewhat easier using Python's [list comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions):

In [12]:
def distances(pt,others): return [distance(pt,other) for other in others]

As we strive here for the *simplest readable code*, we will choose to use list comprehensions in cases such as this one where they more directly communicate our intentions.

We often want to select only the atoms that are nearby another atom. We can *filter* our list for distances that are less than a certain amount:

In [86]:
def neighbors(distances,cutoff):
    def close(d): return d<cutoff
    return list(filter(close,distances))

Here we define an inline function `close` that returns `True` for values less than the cutoff. `filter` then selects values from the `distances` where that function is true. We use the `list` function on the result to return a normal Python list rather than an interator, which is slightly less efficient, but more convenient for interactive work such as we're doing in this notebook.

We could have also used an [anonymous function](https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions) `lambda` to define the `close` function:

In [87]:
def neighbors(distances,cutoff): return list(filter(lambda d: d<cutoff,distances))

You can decide for yourself what makes the simplest readable code; the author somewhat prefers the inline function.

To show how these functions work, let's create a cube of atoms $10\times 10\times 10$ centered at the origin, using the `numpy` `rand` function:

In [88]:
def pointcube(N,D):
    pts = []
    for _ in range(N):
        pt = np.random.rand(3)
        pts.append(D*(pt-0.5)) # Uses broadcasting to subtract 0.5 from each coordinate
    return pts

In [99]:
pts = pointcube(20,10)
pts # Convenient way to print out the return value

[array([-2.93894875,  3.5767089 , -2.18365153]),
 array([-1.3545747 , -4.97516909,  3.63380839]),
 array([-4.75595972,  3.36205424,  2.72451511]),
 array([ 3.93026362, -2.49349639,  1.79520942]),
 array([4.4612889 , 1.88817557, 4.76964075]),
 array([-1.652398  ,  1.95548737, -1.72504479]),
 array([-2.04992563,  2.88193644, -4.19130666]),
 array([-3.46078445,  1.1096685 , -0.49803062]),
 array([ 2.09748929,  1.33645256, -0.92436616]),
 array([-4.34105368,  3.7261747 ,  1.28669498]),
 array([-3.90189268,  3.01707821, -2.41741812]),
 array([-2.89340135, -3.80725797, -1.49813072]),
 array([-2.69606728, -4.8654297 , -1.62226206]),
 array([2.40335897, 2.79581112, 0.68526302]),
 array([ 3.65627165, -4.36414524, -2.2356358 ]),
 array([ 4.4310181 , -2.95661094,  3.65818409]),
 array([-2.06474919, -4.2201647 ,  2.2870665 ]),
 array([ 0.91141151, -0.13444479,  0.63815458]),
 array([ 1.51598851, -3.29442721, -1.07215626]),
 array([-3.43002419,  4.3730258 , -4.99217856])]

In [100]:
origin = coord(0,0,0)
ds = distances(origin,pts)
ds

[5.11845682990897,
 6.30806971157537,
 6.430050091395783,
 4.988714586527503,
 6.7983658681955275,
 3.0870907844671893,
 5.484049987338074,
 3.668300384901779,
 2.65330352390845,
 5.863847619441574,
 5.492853334865442,
 5.01112564657672,
 5.794214281890332,
 3.7499706091715828,
 6.116547516868875,
 6.46202603334915,
 5.225289706762559,
 1.1207085288789247,
 3.7816650944889783,
 7.4706269751570025]

In [101]:
ns = neighbors(ds,3)
ns

[2.65330352390845, 1.1207085288789247]

In [105]:
raise Exception("finish fast neighbor list calculation")

Exception: finish fast neighbor list calculation

## Representing atoms

## Fast methods of computing Coulomb repulsion